language: c

matrix:
  include:
  - os: linux
    env: TARGET_NAME=Linux
    dist: trusty
    sudo: false
    compiler: gcc
  - os: osx
    env: TARGET_NAME=OSX
    osx_image: xcode8
    compiler: gcc

addons:
  apt:
    packages:
    - p7zip-full
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libxmu-dev
    - libxi-dev
    - libglew-dev
    - libexpat-dev
    - libasound-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew p7zip; fi

script:
  - make release
  - 7z a "Colditz_Escape_${TARGET_NAME}.7z" "Colditz Escape"
