language: c

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    compiler: gcc
  - os: osx
    osx_image: xcode8
    compiler: gcc

addons:
  apt:
    packages:
    - p7zip-full
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libxmu-dev
    - libxi-dev
    - libglew-dev
    - libexpat-dev
    - libasound-dev

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make release