os: Visual Studio 2017

environment:
  matrix:
  - WINDOWS: Release
  - PSP: Release

build:
  project: colditz.sln
  parallel: true
  verbosity: detailed

install:
# Wow, as per http://www.yamllint.com/, yaml is SUPER
# SENSITIVE to indentations when using "ps: |-"
- ps: |-
      if ($env:PSP) {
        Invoke-WebRequest -UserAgent 'Chrome' -outfile pspsdk-setup.exe https://sourceforge.net/projects/minpspw/files/SDK%20%2B%20devpak/pspsdk%200.11.2/pspsdk-setup-0.11.2r3.exe
        7z x pspsdk-setup.exe -oPSPSDK -y
      }

build_script:
- ps: |-
      if ($env:WINDOWS) {
        msbuild colditz.sln /m /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
        7z a "Colditz_Escape_Windows.7z" "Colditz Escape" -x!"*/*.PMP"
      } elseif ($env:PSP) {
        $env:Path  += ";" + $env:APPVEYOR_BUILD_FOLDER + "\PSPSDK\bin"
        make release
        7z a "Colditz_Escape_PSP.7z" "Colditz Escape" -x!"*/*.AVI" -x!"*/SHADERS"
      }

artifacts:
- path: '*.7z'
  name: Colditz Escape

deploy:
  release: $(appveyor_repo_tag_name)
  description: Colditz Escape $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token: # GitHub token, encrypted from https://ci.appveyor.com/tools/encrypt
    secure: 5NZvhqfqbVQHZ74SkiWihhvQiTAytO/M2KU4j9EBdkxWuY1Pr35ed5BFJ8ZGYAUV
  artifact: /.*7z/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
