os: Visual Studio 2017

init:
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\PSPSDK\bin
  - set PSPSDK=%APPVEYOR_BUILD_FOLDER%\PSPSDK\psp\sdk

environment:
  matrix:
    - CONFIGURATION: Debug
      PLATFORM: Windows
    - CONFIGURATION: Release
      PLATFORM: Windows
    - CONFIGURATION: Release
      PLATFORM: PSP

build:
  project: colditz.sln
  parallel: true
  verbosity: detailed

install:
  - curl -o pspsdk-setup.exe -L https://sourceforge.net/projects/minpspw/files/SDK%20%2B%20devpak/pspsdk%200.11.2/pspsdk-setup-0.11.2r3.exe
  - 7z x pspsdk-setup.exe -o PSPSDK

build_script:
  - if [%PLATFORM%]==[Windows] msbuild colditz.sln /m /p:Configuration=%CONFIGURATION% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - if [%PLATFORM%]==[PSP] make"
